checking github-pages

diff --git a/.github/workflows/any-pr.yml b/.github/workflows/any-pr.yml
--- a/.github/workflows/any-pr.yml
+++ b/.github/workflows/any-pr.yml
@@ -13,17 +13,32 @@ jobs:
         with:
           fetch-depth: 0
 
-      - name: Get labels
-        id: labels
-        uses: iits-consulting/action-get-project-metadata@main
-        env:
-          API_TOKEN_GITHUB: ${{ secrets.DLAVRUSHKO_PERSONAL_ACCESS_TOKEN }}
-        with:
-          destination_repo: 'iits-consulting/helm-charts'
-          type: labels
+      - name: TEMP Get valid SHA
+        run: |
+        echo ${{github.sha}}
+        echo ${{ github.event.pull_request.base.sha }}
 
-      - name: Read labels
-        run: echo ${{ steps.labels.outputs }}
+#      - name: Get pull requests
+#        id: pr-labels
+#        uses: iits-consulting/action-get-project-metadata@main
+#        env:
+#          API_TOKEN_GITHUB: ${{ secrets.DLAVRUSHKO_PERSONAL_ACCESS_TOKEN }}
+#        with:
+#          destination_repo: 'iits-consulting/helm-charts'
+#          type: pull-requests
+
+
+
+#      - name: Read labels
+#        run: |
+#          CHART_NAME=$(echo ${{ steps.pr-labels.outputs }}\
+#          | jq -r -c 'map(select(.head.sha | contains("6d3d413c60dce9da8488ca8458dabb81a96f2e8c")) \
+#          | .labels[] | select(.name | contains("chartName")) | .name)')
+#          if [[ -z $CHART_NAME ]]; then
+#            echo "ERROR: Actual PR does not have chartName label"
+#            exit 1
+#          fi
+
 #2
 #      - name: helm-check
 #        uses: igabaydulin/helm-check-action@0.1.4
